metadata.format.version = "1.1"

[versions]

# CompileOnly dependencies
velocity = "3.3.0-SNAPSHOT"
paper = "1.21-R0.1-SNAPSHOT"
minestom-server = "7320437640"
minestom-extensions = "1.2.0"
minecraft = "1.21"

# Gradle Plugins
blossom = "2.1.0"
shadow = "8.1.8"
runvelocity = "2.3.0"

bstats = "3.0.2"

fabric-api = "0.101.2+1.21"
fabric-loader = "0.16.0"

[libraries]

# Compile Only Dependencies
velocity-api = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
velocity-proxy = { group = "com.velocitypowered", name = "velocity-proxy", version.ref = "velocity" }
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
minestom-server = { module = "net.minestom:minestom-snapshots", version.ref = "minestom-server" }
minestom-extensions = { module = "dev.hollowcube:minestom-ce-extensions", version.ref = "minestom-extensions" }
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }

fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }

bstats = { module = "org.bstats:bstats-velocity", version.ref = "bstats" }

packetevents = { group = "com.github.retrooper", name = "packetevents-velocity", version = "2.4.0" }
vpacketevents = { group = "io.github.4drian3d", name = "vpacketevents-api", version = "1.1.0" }

annotations = "org.jetbrains:annotations:24.1.0"
slf4j = "org.slf4j:slf4j-api:2.0.16"

[plugins]

blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
shadow = { id = "io.github.goooler.shadow", version.ref = "shadow" }
runvelocity = { id = "xyz.jpenilla.run-velocity", version.ref = "runvelocity" }
runpaper = { id = "xyz.jpenilla.run-paper", version.ref = "runvelocity" }
pluginyml-paper = { id = "net.minecrell.plugin-yml.paper", version = "0.6.0" }
idea-ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version = "1.1.8" }
