metadata.format.version = "1.1"

[versions]

# CompileOnly dependencies
velocity = "3.4.0-SNAPSHOT"
paper = "1.21.8-R0.1-SNAPSHOT"
minestom-server = "2025.10.05-1.21.8"
minecraft = "1.21.9-rc1"

# Gradle Plugins
blossom = "2.2.0"
shadow = "9.3.2"
runvelocity = "3.0.2"

bstats = "3.2.1"

fabric-api = "0.133.14+1.21.9"
fabric-loader = "0.18.4"

[libraries]

# Compile Only Dependencies
velocity-api = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
velocity-proxy = { group = "com.velocitypowered", name = "velocity-proxy", version.ref = "velocity" }
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
minestom-server = { module = "net.minestom:minestom", version.ref = "minestom-server" }
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }

fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }

bstats = { module = "org.bstats:bstats-velocity", version.ref = "bstats" }

packetevents-velocity = { group = "com.github.retrooper", name = "packetevents-velocity", version = "2.11.2" }
packetevents-paper = { group = "com.github.retrooper", name = "packetevents-spigot", version = "2.11.2" }
vpacketevents = { group = "io.github.4drian3d", name = "vpacketevents-api", version = "1.1.0" }

annotations = "org.jetbrains:annotations:26.1.0"
slf4j = "org.slf4j:slf4j-api:2.0.17"

[plugins]

blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
runvelocity = { id = "xyz.jpenilla.run-velocity", version.ref = "runvelocity" }
runpaper = { id = "xyz.jpenilla.run-paper", version.ref = "runvelocity" }
pluginyml-paper = { id = "de.eldoria.plugin-yml.paper", version = "0.8.0" }
idea-ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version = "1.4.1" }
